version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flyrank_ass
    environment:
      POSTGRES_USER: iapan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: product_db
    
    ports:
      - "5432:5432"
    
    volumes:
      - data_for_flyrank:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data_for_flyrank: