version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flyrank_ass
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    
    ports:
      - "${DB_PORT}:${DB_PORT}"
    
    volumes:
      - data_for_flyrank:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db 
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

volumes:
  data_for_flyrank: